USE NOVA_Market;
GO

SET NOCOUNT ON;
GO


/* =========================================================
   NOVA Market BI
   DimGeography Data Quality Validation

   Source:
   conformed.Geography

   Target:
   dwh.DimGeography

   Grain:
   1 row = 1 ZIP code prefix

   Expected:
   19,177 business rows
   + 1 Unknown member
   ========================================================= */


/* =========================================================
   1. Row Count / Key Range
   ========================================================= */

SELECT
    COUNT(*) AS [RowCount],

    SUM(
        CASE
            WHEN GeographyKey <> 0
            THEN 1
            ELSE 0
        END
    ) AS BusinessRows,

    COUNT(
        DISTINCT
        CASE
            WHEN GeographyKey <> 0
            THEN ZipCodePrefix
        END
    ) AS DistinctBusinessZIPs,

    SUM(
        CASE
            WHEN GeographyKey = 0
            THEN 1
            ELSE 0
        END
    ) AS UnknownMembers,

    MIN(GeographyKey) AS MinGeographyKey,
    MAX(GeographyKey) AS MaxGeographyKey

FROM dwh.DimGeography;
GO


/* =========================================================
   2. Unknown Member
   ========================================================= */

SELECT
    GeographyKey,
    ZipCodePrefix,
    CityName,
    StateCode
FROM dwh.DimGeography
WHERE GeographyKey = 0;
GO


/* =========================================================
   3. Business Key Uniqueness
   ========================================================= */

SELECT
    ZipCodePrefix,
    COUNT(*) AS DuplicateRows
FROM dwh.DimGeography
WHERE GeographyKey <> 0
GROUP BY ZipCodePrefix
HAVING COUNT(*) > 1;
GO


/* =========================================================
   4. Geography Characteristics
   ========================================================= */

SELECT
    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND CityName IS NULL
            THEN 1
            ELSE 0
        END
    ) AS NullCities,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND HasCoordinates = 0
            THEN 1
            ELSE 0
        END
    ) AS ZIPsWithoutCoordinates,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND MissingFromGeolocationFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS MissingFromGeolocation,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND StateConflictFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS StateConflicts,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND StateAmbiguousFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS StateAmbiguous,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND CityAmbiguousFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS CityAmbiguous,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND CityResolvedByReferenceFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS CitiesResolvedByReference,

    SUM(
        CASE
            WHEN GeographyKey <> 0
             AND ReferenceFallbackFlag = 1
            THEN 1
            ELSE 0
        END
    ) AS ReferenceFallbackZIPs

FROM dwh.DimGeography;
GO


/* =========================================================
   5. Conformed ZIP Coverage
   ========================================================= */

SELECT
    COUNT(*) AS MissingConformedZIPsInDimGeography
FROM conformed.Geography c
LEFT JOIN dwh.DimGeography d
    ON c.ZipCodePrefix = d.ZipCodePrefix
WHERE d.GeographyKey IS NULL;
GO


/* =========================================================
   6. Source -> Target Exact Comparison

   GeographyKey is intentionally excluded because it is
   generated by the DWH destination.
   ========================================================= */

WITH SourceData AS
(
    SELECT
        ZipCodePrefix,
        CityName,
        StateCode,

        RepresentativeLatitude,
        RepresentativeLongitude,

        CASE
            WHEN RepresentativeLatitude IS NOT NULL
             AND RepresentativeLongitude IS NOT NULL
            THEN CAST(1 AS BIT)
            ELSE CAST(0 AS BIT)
        END AS HasCoordinates,

        MissingFromGeolocationFlag,
        StateConflictFlag,
        StateAmbiguousFlag,
        StateResolvedByReferenceFlag,

        CityAmbiguousFlag,
        CityResolvedByReferenceFlag,
        ReferenceFallbackFlag

    FROM conformed.Geography
)
SELECT
    COUNT(*) AS SourceRowsMissingOrDifferentInDWH
FROM
(
    SELECT *
    FROM SourceData

    EXCEPT

    SELECT
        ZipCodePrefix,
        CityName,
        StateCode,

        RepresentativeLatitude,
        RepresentativeLongitude,

        HasCoordinates,

        MissingFromGeolocationFlag,
        StateConflictFlag,
        StateAmbiguousFlag,
        StateResolvedByReferenceFlag,

        CityAmbiguousFlag,
        CityResolvedByReferenceFlag,
        ReferenceFallbackFlag

    FROM dwh.DimGeography
    WHERE GeographyKey <> 0
) x;
GO


/* =========================================================
   7. Target -> Source Exact Comparison
   ========================================================= */

WITH SourceData AS
(
    SELECT
        ZipCodePrefix,
        CityName,
        StateCode,

        RepresentativeLatitude,
        RepresentativeLongitude,

        CASE
            WHEN RepresentativeLatitude IS NOT NULL
             AND RepresentativeLongitude IS NOT NULL
            THEN CAST(1 AS BIT)
            ELSE CAST(0 AS BIT)
        END AS HasCoordinates,

        MissingFromGeolocationFlag,
        StateConflictFlag,
        StateAmbiguousFlag,
        StateResolvedByReferenceFlag,

        CityAmbiguousFlag,
        CityResolvedByReferenceFlag,
        ReferenceFallbackFlag

    FROM conformed.Geography
)
SELECT
    COUNT(*) AS DWHRowsMissingOrDifferentInSource
FROM
(
    SELECT
        ZipCodePrefix,
        CityName,
        StateCode,

        RepresentativeLatitude,
        RepresentativeLongitude,

        HasCoordinates,

        MissingFromGeolocationFlag,
        StateConflictFlag,
        StateAmbiguousFlag,
        StateResolvedByReferenceFlag,

        CityAmbiguousFlag,
        CityResolvedByReferenceFlag,
        ReferenceFallbackFlag

    FROM dwh.DimGeography
    WHERE GeographyKey <> 0

    EXCEPT

    SELECT *
    FROM SourceData
) x;
GO


/* =========================================================
   8. Overall Validation
   ========================================================= */

SELECT
    CASE
        WHEN
            (SELECT COUNT(*)
             FROM dwh.DimGeography) = 19178

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey = 0) = 1

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0) = 19177

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND CityName IS NULL) = 20

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND HasCoordinates = 0) = 162

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND MissingFromGeolocationFlag = 1) = 162

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND StateConflictFlag = 1) = 8

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND StateAmbiguousFlag = 1) = 0

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND CityAmbiguousFlag = 1) = 20

        AND
            (SELECT COUNT(*)
             FROM dwh.DimGeography
             WHERE GeographyKey <> 0
               AND CityResolvedByReferenceFlag = 1) = 12

        THEN 'DIM GEOGRAPHY VALIDATION PASSED'

        ELSE 'DIM GEOGRAPHY VALIDATION FAILED'
    END AS DimGeographyValidationStatus;
GO